### ISSUE TITLE
Change default when adding new rule to ip address 0.0.0.0/0

### ISSUE THREAD

**Issue by col-panic** [redmineup/redmine_access_filters#3]
When adding a new rule, the ip address default should be set to 0.0.0.0/0, as otherwise adding an "empty" rule leads to a total lock-out. Or the other way round, an empty ip address area should be treated as no limitation, which equals 0.0.0.0/0

I additionally propose to rename the field to something like "Limit access to address range(s)".

**Comment by k41n** [comment]
Resolved in 33913cb

**Comment by col-panic** [comment]
Works as expected, thanks!
